# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

jobs:
  pr-checks:
    name: Checks
    uses: seL4/ci-actions/.github/workflows/pr.yml@workflows

  preprocess:
    name: Preprocess
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, ARM_HYP, AARCH64, RISCV64, X64]
        feature: ["", MCS]
        exclude:
          - arch: ARM_HYP
            feature: MCS
          - arch: AARCH64
            feature: MCS
          - arch: X64
            feature: MCS
    steps:
    - uses: seL4/ci-actions/preprocess@master
      with:
        L4V_ARCH: ${{ matrix.arch }}
        L4V_FEATURES: ${{ matrix.feature }}
