# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# xmllint for seL4 IDL files

name: XML

on:
  push:
    branches:
      - master
    paths:
      - 'libsel4/**/sel4*.xml'
      - 'libsel4/**/sel4*.xsd'
  pull_request:
    paths:
      - 'libsel4/**/sel4*.xml'
      - 'libsel4/**/sel4*.xsd'

jobs:
  xmllint:
    name: XML Lint
    runs-on: ubuntu-latest
    steps:
    - name: install xmllint
      run: sudo apt-get install libxml2-utils
    - uses: actions/checkout@v2
    - name: run xmllint
      run: |
        find libsel4 -name "sel4*.xml" | \
        xargs xmllint --schema libsel4/tools/sel4_idl.xsd --noout
